version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tickets}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tickets}
      POSTGRES_DB: ${POSTGRES_DB:-tickets}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 10
  
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "8025:8025"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-tickets}:${POSTGRES_PASSWORD:-tickets}@db:5432/${POSTGRES_DB:-tickets}?schema=public
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate dev --name init && npm run dev"

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - api
    volumes:
      - ./web:/app
      - /app/node_modules
    command: npm run start

volumes:
  db_data:
